### ISSUE TITLE
Crashes Dedicated Server - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by nephatrine** [TheIcyOne/ParrotPower#1]
It works in singleplayer. On a server I can place the block, but as soon as I start things up the server crashes with this error. Maybe it's trying to call a clientside function?

https://pastebin.com/saB5kd55

This makes my parrot and I very sad. Any help would be very appreciated.

- Minecraft 1.12.2
- forge-1.12.2-14.23.5.2838
- parrotpower-1.3.3.jar

**Comment by TheIcyOne** [comment]
Well I have no idea why that never crashed before, but this is fixed in 1.3.4 unless I've been a big dum
